# Generated by Django 4.0.4 on 2022-06-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('time', models.DateTimeField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
            ],
        ),
    ]
