# Generated by Django 4.0.4 on 2022-06-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThoiGian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheDoTimKiem', models.BooleanField(default=False)),
                ('ThoiGianBatDau', models.DateTimeField(max_length=255)),
                ('THoiGianKetThuc', models.DateTimeField(max_length=255)),
            ],
        ),
    ]
