# Generated by Django 4.0.2 on 2022-07-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiotapi', '0004_alter_thoigian_thoigianketthuc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoigian',
            name='ThisMonth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thoigian',
            name='ThisWeek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thoigian',
            name='ToDay',
            field=models.BooleanField(default=False),
        ),
    ]
